version: "3.8"

services:
  cicd_pipeline:
    # image: jenkins/jenkins:lts-alpine
    image: ${DOCKER_REGISTRY-}jenkins
    container_name: cicd_pipeline
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: C:\Docker_Volumes\jenkins_home
        target: /var/jenkins_home
    ports: 
      - 8888:8080
      - 50000:50000
    networks: 
      - test-environment
    restart: always

  rabbitmq_testenv:
    image: rabbitmq:3-alpine
    container_name: rabbitmq_testenv
    networks: 
      - test-environment
    restart: always

  sqlserver_testenv:
    container_name: sqlserver_testenv
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@#123
      - MSSQL_PID=Express
    networks: 
      - test-environment
    restart: always

networks: 
  test-environment:
    driver: bridge